---
name: BlockParticle
author:  Ad5001
version: 1.0
api: [3.0.0-ALPHA8]
load: POSTWORLD
main: Ad5001\BlockParticle\Main
commands:
 getparticleblock:
   description: "Get a particle block !"
   usage: "/gpb <particle> [true | false (solid or not)]"
   permission: blockparticle.get
   aliases: [gpb]
 deleteparticleblock:
   description: "Delete the particleblock which is underneath you."
   usage: "/dpb"
   permission: blockparticle.remove
   aliases: [dpb]
permissions: 
 blockparticle.get:
   default: op
 blockparticle.place:
   default: op
 blockparticle.remove:
   default: op
...
